version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "${PORT:-5672}:${PORT:-5672}"
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${USER:-docker}
      - RABBITMQ_DEFAULT_PASS=${PASSWORD:-docker}
  micro-ci-docker-runner:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      RABBIT_HOST: ${RABBIT_HOST:-rabbitmq}
      RABBIT_USER: ${RABBIT_USER:-docker}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD:-docker}
      RABBIT_PORT: ${RABBIT_PORT:-5672}
      RABBIT_RUNNER_QUEUE: ${RABBIT_RUNNER_QUEUE:-docker}
      FOLDER_TAR: ${FOLDER_TAR:-.}
      FOLDER_PROJECTS: ${FOLDER_PROJECTS:-.}
      RABBIT_EVENT_QUEUE: ${RABBIT_EVENT_QUEUE:-events}
    restart: always
    privileged: true
    volumes:
      - al2projects:/var/projects
    depends_on:
      - rabbitmq

volumes:
  al2projects:
    external: true
