version: "3.4"

services:
  micro-ci-docker-runner:
    image: esgimicroci/al2-docker-runner
    container_name: al2-docker-runner
    environment:
      HOST: ${HOST}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      PORT: ${PORT}
      QUEUE: ${QUEUE}
    restart: always

# Add your networks/volumes/services for your microservice
