version: "3.4"

services:
  micro-ci-docker-runner:
    image: esgimicroci/al2-docker-runner
    container_name: al2-docker-runner
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_RUNNER_QUEUE: ${RABBIT_RUNNER_QUEUE}
      FOLDER_TAR: ${FOLDER_TAR:-/var/tar}
      FOLDER_PROJECTS: ${FOLDER_PROJECTS:-/var/projects}
      RABBIT_EVENT_QUEUE: ${RABBIT_EVENT_QUEUE:-events}
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - al2projects:/var/projects

volumes:
  al2projects:
    external: true
# Add your networks/volumes/services for your microservice
